### ISSUE TITLE
Resnet18 NHWC HWIO end-to-end with hacks

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/glenside#72]

**Comment by gussmith23** [comment]
I need to add a layout parameter for global_avg_pool2d.

**Comment by gussmith23** [comment]
See #73

**Comment by gussmith23** [comment]
I think there's a problem with how NHWC/HWIO layouts are getting parsed from Relay. I'm getting this error when adding the parsed Glenside expression to the egraph:
```
thread 'resnet18_nhwc_hwio_end_to_end_with_opaque_operators' panicked at 'assertion failed: total_dim_len >= kernel_dim_len', /Users/gus/.cargo/git/checkouts/glenside-bc6f450c125506d6/10f6baf/src/language/language.rs:946:13
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:505
   1: glenside::language::language::access_windows_resulting_shape::{{closure}}
             at /Users/gus/.cargo/git/checkouts/glenside-bc6f450c125506d6/10f6baf/src/language/language.rs:946
   2: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:280
   3: core::option::Option<T>::map
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:437
   4: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:914
   5: alloc::vec::Vec<T>::extend_desugared
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:2433
   6: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:2356
   7: <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:2139
   8: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:2162
   9: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:2001
  10: core::iter::traits::iterator::Iterator::collect
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1637
  11: glenside::language::language::access_windows_resulting_shape
             at /Users/gus/.cargo/git/checkouts/glenside-bc6f450c125506d6/10f6baf/src/language/language.rs:938
  12: <glenside::language::language::MyAnalysis as egg::language::Analysis<glenside::language::language::Language>>::make
             at /Users/gus/.cargo/git/checkouts/glenside-bc6f450c125506d6/10f6baf/src/language/language.rs:2458
  13: egg::egraph::EGraph<L,N>::add::{{closure}}
             at /Users/gus/.cargo/git/checkouts/egg-e5acb91d4b155ec9/39415f1/src/egraph.rs:296
  14: core::option::Option<T>::unwrap_or_else
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:411
  15: egg::egraph::EGraph<L,N>::add
             at /Users/gus/.cargo/git/checkouts/egg-e5acb91d4b155ec9/39415f1/src/egraph.rs:290
  16: egg::egraph::EGraph<L,N>::add_expr
             at /Users/gus/.cargo/git/checkouts/egg-e5acb91d4b155ec9/39415f1/src/egraph.rs:235
  17: resnet18_NHWC_HWIO_end_to_end_with_opaque_operators::resnet18_nhwc_hwio_end_to_end_with_opaque_operators
             at ./tests/resnet18-NHWC-HWIO-end-to-end-with-opaque-operators.rs:59
  18: resnet18_NHWC_HWIO_end_to_end_with_opaque_operators::resnet18_nhwc_hwio_end_to_end_with_opaque_operators::{{closure}}
             at ./tests/resnet18-NHWC-HWIO-end-to-end-with-opaque-operators.rs:24
  19: core::ops::function::FnOnce::call_once
             at /Users/gus/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  20: core::ops::function::FnOnce::call_once
             at /rustc/8b4085359ae798dedb05c95ad42520557bd25320/library/core/src/ops/function.rs:227
```

So it seems like an access-windows is being used badly somewhere. Must be in the convolution?

**Comment by gussmith23** [comment]
Fixed

**Comment by gussmith23** [comment]
Now having the problem: if the ILP extraction isn't perfect, then eclasses might have more than one node extracted. So when we pull out eclasses from the solution, we need to filter out invalid enodes (i.e. ones that don't have their children extracted).

**Comment by gussmith23** [comment]
In some sense, this situation isn't that much better than just starting from a full egraph. Now, we need to figure out how to filter out a real expression from an egraph that still has multiple enodes per eclass, though maybe it has fewer enodes per eclass than the full egraph.

**Comment by gussmith23** [comment]
Actually, part of the problem is that I'm passing the original egraph into codegen. This is partly because it's easier to generate the worklist for the original egraph, because we have the topo_sort vars...but we could generate a new egraph and convert the vars.

**Comment by gussmith23** [comment]
Almost there. Everything seems to be right in the generated code except until the very end:
```
1871    for (int i = 0; i < 50176; i++) {
(gdb) l
1866     int b_shape_add_K74YLIgg1hJft7YyEOg4VWYJP51mJ4[1] = {1000};                            
1867    add_with_broadcasting((float*) relay_op_add_out_Yrp6GfTdXk0JJdkIfXfTfgExjMi5Rd, (float*) access_reshape_out_eFLsGfHCbFdTBxwOd8Cn41etnG7yZl, (float*) fc1_bias, (int*)  out_shape_add_dZe5gD9ipTyfkgc5HM8dFUJJV6iuPN, 2, (int*) a_shape_add_x5xPYwy7SddEwm6uWY6h01mZOFaTTJ, 2, (int*) b_shape_add_K74YLIgg1hJft7YyEOg4VWYJP51mJ4, 1);
1868
1869    softmax1D((float*) relay_op_add_out_Yrp6GfTdXk0JJdkIfXfTfgExjMi5Rd, (float*) relay_op_softmax_out_96g7hqAAGIhholsctnfsXDqBbuAOBa, 1000);
1870
1871    for (int i = 0; i < 50176; i++) {
1872      ((float*)out)[i] = ((float*)transpose_out_dFTXHv5AIaHoGO7yf4WA6DwICXC8er)[i];
1873    }
1874    }
(gdb) l
Line number 1875 out of range; /tmp/resnet.c has 1874 lines.
```
the thing coming out of softmax is correct, but then out gets assigned the value from the transpose, which, where is that even coming from? So something is out of order, apparently.

**Comment by gussmith23** [comment]
Ah, I wasn't converting the old root id to the new root id when extracting the new egraph. That's probably not the last time that bug will happen...
